package testeos.Views;

public enum AdminStorageMenuOptions {
    MENU,
    PESCADOS,
    PESCADOS_AGUADULCE,
    PESCADOS_MARISCOS,
    PESCADOS_AGUASALADA,
    PESCADOS_AGUASALADA2,
    CARNES,
    CARNES_CARNE,
    CARNES_POLLO,
    CARNES_CERDO,
    VERDURAS,
    UTENSILIOS
}
